services:
    # Laravel Application (PHP-FPM)
    app:
        image: justinlaureano/swarm-demo-app:latest
        command: sh -c "php-fpm"
        deploy:
            replicas: 2
            placement:
                constraints:
                    - "node.labels.db!=true"
            restart_policy:
                condition: on-failure
        environment:
            - APP_ENV=production
            - APP_KEY=base64:avKE3p0wqZ9E1wqrWJwK/HIIILzoO+W8DoUxVniwimY=
            - APP_DEBUG=false
        networks:
            - swarm-demo

    # Nginx Service
    web:
        image: justinlaureano/swarm-demo-web:latest
        command: sh -c "/var/www/wait-for-it.sh app:9000 -t 120 && nginx -g \"daemon off;\""
        deploy:
            replicas: 2
            placement:
                constraints:
                    - "node.labels.db!=true"
            restart_policy:
                condition: on-failure
        ports:
            - "80:80"
        networks:
            - swarm-demo
        depends_on:
            - app

    mysql:
        image: justinlaureano/swarm-demo-mysql:latest
        deploy:
            replicas: 2
            placement:
                constraints:
                    - "node.labels.db==true"
            restart_policy:
                condition: any
        volumes:
            - type: volume
              source: mysqldata
              target: /var/lib/mysql
        environment:
        - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}

    redis:
        image: redis:7.4.0-alpine
        deploy:
            placement:
                constraints:
                    - "node.labels.db==true"
        volumes:
            - type: volume
              source: redisdata
              target: /data

networks:
    swarm-demo:
        driver: overlay
        attachable: true

volumes:
    mysqldata:
    redisdata: