services:
    # Laravel Application (PHP-FPM)
    app:
        image: justinlaureano/swarm-demo-app:latest
        command: sh -c "php-fpm"
        deploy:
            replicas: 2
            restart_policy:
                condition: on-failure
        environment:
            - APP_ENV=production
            - APP_KEY=base64:avKE3p0wqZ9E1wqrWJwK/HIIILzoO+W8DoUxVniwimY=
            - APP_DEBUG=false
        networks:
            - swarm-demo

    # Nginx Service
    web:
        image: justinlaureano/swarm-demo-web:latest
        command: sh -c "/var/www/wait-for-it.sh app:9000 -t 120 && nginx -g \"daemon off;\""
        deploy:
            replicas: 2
            restart_policy:
                condition: on-failure
        ports:
            - "80:80"
        networks:
            - swarm-demo
        depends_on:
            - app

networks:
    swarm-demo:
        driver: overlay
        attachable: true
