services:
    # Laravel Application (PHP-FPM)
    app:
        image: justinlaureano/swarm-demo-app:latest
        command: sh -c "php-fpm"
        deploy:
            replicas: 3
            restart_policy:
                condition: any
                delay: 5s
                max_attempts: 3
                window: 15s
        healthcheck:
            test: [ "CMD", "nc", "-zv", "localhost", "9000" ]
            interval: 30s
            timeout: 5s
            retries: 3
            start_period: 40s
        environment:
            # - APP_ENV=production
            - APP_KEY=base64:avKE3p0wqZ9E1wqrWJwK/HIIILzoO+W8DoUxVniwimY=
            - APP_DEBUG=false
        networks:
            - app-network

    # Nginx Service
    web:
        image: justinlaureano/swarm-demo-web:latest
        deploy:
            replicas: 3
            restart_policy:
                condition: any
                delay: 10s
                max_attempts: 50
                window: 15s
        ports:
            - "80:80"
        networks:
            - app-network
        depends_on:
            - app

networks:
    app-network:
        driver: overlay

volumes:
    db-data:
    redis-data:
